//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdditionalData
    {
        public int ID { get; set; }
        public string aspnetUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ExecutiveTitle { get; set; }
        public string Gender { get; set; }
        public string ProfileImage { get; set; }
        public string UserBio { get; set; }
    }
}
